name: Deploy Package to Release Branch

on:
  #workflow_dispatch:
  
  push:
    tags:
      - '[0-9]*'
    #branches:
    #  - master 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Push Package to 'release' branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: Packages/com.kaijusolutions.agents
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "ver: {msg}"
          # If triggered by a tag, use that tag. If manual, leave tag empty.
          TAG: ${{ github.ref_type == 'tag' && github.ref_name || '' }}